server:
  port: 8081

spring:
  profiles:
    active: live

# spring.batch.job.names: ${job.name:NONE}

---
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  batch:
    job:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/good_choice
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    template:
      default-topic: point
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  logging:
    level:
      org.hibernate.SQL: debug
  config:
    activate:
      on-profile: live
